services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"

  express:
    build:
      context: ./express-app
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      PORT: 3000
    ports:
      - "3000:3000"

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - express
      - postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
    networks:
      - default

networks:
  default:
    driver: bridge
